
function videos() {
return  [
    { id: 'queen', name: 'Queen Bee', details: 'The Queen of the collection has got amazing bone structure, alongside determination and an agenda! Step away define her head shape and work with the facial characteristics - working hair with your hands to create this beautiful shape.', credits: "Hair by: Andrew Jose and Evelina Lundgren, Makeup by: Julia Wilson, Fashion Styling: Rhona Emma, Photography: Alex Barron-Hough, Products: TIGI Copyright colour and Catwalk, Text by: Salon News Asia professional hair magazine" },
    { id: 'beach blonde', name: 'Beach Blonde', details: "Blonde it up with the cleanest iciest blonde on the market! Feel confident in your skin and cut your hair short, don't just change your length, discover a change in attitude. Focusing on what brings out the detail on the face, this hair was both cut and bleached.", credits: "Hair by: Andrew Jose and Evelina Lundgren, Makeup by: Julia Wilson, Fashion Styling: Rhona Emma, Photography: Alex Barron-Hough, Products: TIGI Copyright colour and Catwalk, Text by: Salon News Asia professional hair magazine" },
    { id: 'julia', name: 'Sunset Sleek', details: "A sleek elegant shape with focus on the back to highlight Julia's strong jaw line. Working with TIGI Bodifying Spray to set and define the strong line.", credits: "Hair by: Andrew Jose and Evelina Lundgren, Makeup by: Julia Wilson, Fashion Styling: Rhona Emma, Photography: Alex Barron-Hough, Products: TIGI Copyright colour and Catwalk, Text by: Salon News Asia professional hair magazine" },
    { id: 'yulia', name: 'The 2018s Freckles', details: "Sharp shape with different length accenting movement throughout the  hair. A Salt Spray finish from TIGI gets Julia prepped for the beach party.", credits: "Hair by: Andrew Jose and Evelina Lundgren, Makeup by: Julia Wilson, Fashion Styling: Rhona Emma, Photography: Alex Barron-Hough, Products: TIGI Copyright colour and Catwalk, Text by: Salon News Asia professional hair magazine" },
    { id: 'eva', name: 'Cathy Come Home', details: "A touch of sunshine - peach coloured full fringe to accentuate the definition of Eva's sexy eyes. Layered waves finish.", credits: "Hair by: Andrew Jose and Evelina Lundgren, Makeup by: Julia Wilson, Fashion Styling: Rhona Emma, Photography: Alex Barron-Hough, Products: TIGI Copyright colour and Catwalk, Text by: Salon News Asia professional hair magazine" },
    { id: 'emma', name: 'Heaven On Earth', details: "The sun shining on the red hair reminds of heaven on earth. Soft graduation on the sides and through the back blending into one length on top. Feminine curly finish with detailed separation in the fringe.", credits: "Hair by: Andrew Jose and Evelina Lundgren, Makeup by: Julia Wilson, Fashion Styling: Rhona Emma, Photography: Alex Barron-Hough, Products: TIGI Copyright colour and Catwalk, Text by: Salon News Asia professional hair magazine" },
]
};

module.exports = videos;
//